language:
  - python

python:
  - "2.7"

# Use the new container infrastructure
sudo:
  - false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' > ansible.cfg

script:
  # Fix layout
  - cd ..
  - mv ansible-rust rust
  - cd rust

  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

  # Run local test
  - ansible-playbook tests/test.yml -i tests/inventory --connection=local

  # Run idempotency test
  - rm log
  - ansible-playbook tests/test.yml -i tests/inventory --connection=local | tee log
  - grep ' changed=0 ' log || exit 1

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
